
spring:
  data:
    rest:
      base-path: /data-api
  thymeleaf:
    cache: false
  datasource:
    generate-unique-name: false
    name: tacocloud
#  security:
#    oauth2:
#      client:
#        registration:
#          facebook:
#            clientId: <facebook client id>
#            clientSecret: <facebook client secret>
#            scope: email, public_profile

server:
  port: 8081

myvariables:
  myvars:
    mynumber: 10